# Generated by Django 4.2.7 on 2023-11-21 06:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intolerancias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaEnfermedades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_usuario', models.UUIDField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('enfermedades', models.ManyToManyField(related_name='listas_enfermedades', to='tasks.enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='ListaIntolerancias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_usuario', models.UUIDField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('intolerancias', models.ManyToManyField(related_name='lista_intolerancias', to='tasks.intolerancias')),
            ],
        ),
        migrations.CreateModel(
            name='ListaNecesidades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_usuario', models.UUIDField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaPreferencias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_usuario', models.UUIDField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Necesidades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.TextField(max_length=10)),
                ('telefono', models.TextField(max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('lista_enfermedades', models.ManyToManyField(related_name='usuarios', to='tasks.listaenfermedades')),
                ('lista_intolerancias', models.ManyToManyField(related_name='usuarios', to='tasks.listaintolerancias')),
                ('lista_necesidades', models.ManyToManyField(related_name='usuarios', to='tasks.listanecesidades')),
                ('lista_preferencias', models.ManyToManyField(related_name='usuarios', to='tasks.listapreferencias')),
            ],
        ),
        migrations.AddField(
            model_name='listapreferencias',
            name='preferencias',
            field=models.ManyToManyField(related_name='lista_preferencias', to='tasks.preferencias'),
        ),
        migrations.AddField(
            model_name='listanecesidades',
            name='necesidades',
            field=models.ManyToManyField(related_name='lista_necesidades', to='tasks.necesidades'),
        ),
    ]
