# Generated by Django 4.2.7 on 2023-11-21 07:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intolerancias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaEnfermedades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('enfermedades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='ListaIntolerancias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaNecesidades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaPreferencias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Necesidades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.TextField(max_length=10)),
                ('telefono', models.TextField(max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('lista_enfermedades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.listaenfermedades')),
                ('lista_intolerancias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.listaintolerancias')),
                ('lista_necesidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.listanecesidades')),
                ('lista_preferencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.listapreferencias')),
            ],
        ),
        migrations.AddField(
            model_name='listapreferencias',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
        ),
        migrations.AddField(
            model_name='listapreferencias',
            name='preferencias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.preferencias'),
        ),
        migrations.AddField(
            model_name='listanecesidades',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
        ),
        migrations.AddField(
            model_name='listanecesidades',
            name='necesidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.necesidades'),
        ),
        migrations.AddField(
            model_name='listaintolerancias',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
        ),
        migrations.AddField(
            model_name='listaintolerancias',
            name='intolerancias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.intolerancias'),
        ),
        migrations.AddField(
            model_name='listaenfermedades',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
        ),
    ]
