# Generated by Django 4.2.7 on 2023-12-09 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Intolerancias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Necesidades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=255)),
                ('direccion', models.TextField(max_length=255)),
                ('latitud', models.DecimalField(decimal_places=5, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.TextField(max_length=10)),
                ('telefono', models.TextField(max_length=10)),
                ('password', models.TextField(max_length=255)),
                ('necesidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.necesidades')),
                ('preferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.preferencias')),
            ],
        ),
        migrations.CreateModel(
            name='Platillos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=255)),
                ('descripcion', models.TextField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url_imagen', models.TextField(max_length=255)),
                ('platillo_dia', models.BooleanField(default=False)),
                ('preferencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.preferencias')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ListaPreferencias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.preferencias')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ListaPedidos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.pedidos')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.platillos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ListaNecesidades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('necesidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.necesidades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ListaIntolerancias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intolerancias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.intolerancias')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ListaIngredientes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.ingredientes')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.platillos')),
            ],
        ),
        migrations.CreateModel(
            name='ListaEnfermedades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enfermedades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.enfermedades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ListaAlergias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.ingredientes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientesRestringidos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.ingredientes')),
                ('necesidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.necesidades')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientesProhibidos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.enfermedades')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.ingredientes')),
            ],
        ),
    ]
