# Generated by Django 4.2.7 on 2023-12-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='costoMaximo',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
            preserve_default=False,
        ),
    ]
